# Generated by Django 4.1 on 2022-08-31 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_title_user_name_rename_cat_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_published',
        ),
    ]
